name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Pack
        run: dotnet pack src/TypeUtilities/TypeUtilities.csproj --no-build -o lib
      - name: Test Pacakge Usage
        run: |
          dotnet remove samples/DemoApp/DemoApp.csproj reference src/TypeUtilities.Abstractions/TypeUtilities.Abstractions.csproj
          dotnet remove samples/DemoApp/DemoApp.csproj reference src/TypeUtilities.SourceGenerators/TypeUtilities.SourceGenerators.csproj
          dotnet add samples/DemoApp/DemoApp.csproj package TypeUtilities --prerelease
          dotnet build samples/DemoApp/DemoApp.csproj -c Release
